[[main]]
name = "Research"
url = "/research/"
weight = 1

[[main]]
name = "Writeups"
url = "/writeups/"
weight = 2

[[main]]
name = "Projects"
url = "/projects/"
weight = 3

[[main]]
name = "Tools"
url = "/tools/"
weight = 4

[[main]]
name = "About"
url = "/page/about/"
weight = 5

[[main]]
name = "Contact"
url = "/page/contact/"
weight = 6
